FROM python:slim

WORKDIR /app

COPY requirements.txt .

RUN python3 -m venv .venv
RUN .venv/bin/pip install -r requirements.txt

CMD ["sudo", "/home/ec2-user/.local/bin/gunicorn", "--bind", "0.0.0.0:80", "flaskr:Flask"]
